# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: slice_metrics.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='slice_metrics.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13slice_metrics.proto\"\x93\x02\n\x0cSliceMetrics\x12\x0b\n\x03tti\x18\x01 \x01(\r\x12#\n\x06slices\x18\x02 \x03(\x0b\x32\x13.SliceMetrics.Slice\x1a\xd0\x01\n\x05Slice\x12\x10\n\x08slice_id\x18\x01 \x01(\r\x12\x13\n\x0b\x63\x66g_min_prb\x18\x02 \x01(\r\x12\x13\n\x0b\x63\x66g_max_prb\x18\x03 \x01(\r\x12\x14\n\x0c\x63\x66g_priority\x18\x04 \x01(\r\x12\x13\n\x0b\x64l_rbs_used\x18\x05 \x01(\r\x12\x13\n\x0bul_rbs_used\x18\x06 \x01(\r\x12\x1b\n\x13\x61vg_dl_rbs_per_slot\x18\x07 \x01(\x02\x12\x1b\n\x13\x61vg_ul_rbs_per_slot\x18\x08 \x01(\x02\x12\x11\n\thol_slots\x18\t \x01(\rb\x06proto3'
)




_SLICEMETRICS_SLICE = _descriptor.Descriptor(
  name='Slice',
  full_name='SliceMetrics.Slice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='slice_id', full_name='SliceMetrics.Slice.slice_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cfg_min_prb', full_name='SliceMetrics.Slice.cfg_min_prb', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cfg_max_prb', full_name='SliceMetrics.Slice.cfg_max_prb', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cfg_priority', full_name='SliceMetrics.Slice.cfg_priority', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dl_rbs_used', full_name='SliceMetrics.Slice.dl_rbs_used', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ul_rbs_used', full_name='SliceMetrics.Slice.ul_rbs_used', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='avg_dl_rbs_per_slot', full_name='SliceMetrics.Slice.avg_dl_rbs_per_slot', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='avg_ul_rbs_per_slot', full_name='SliceMetrics.Slice.avg_ul_rbs_per_slot', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hol_slots', full_name='SliceMetrics.Slice.hol_slots', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=299,
)

_SLICEMETRICS = _descriptor.Descriptor(
  name='SliceMetrics',
  full_name='SliceMetrics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tti', full_name='SliceMetrics.tti', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='slices', full_name='SliceMetrics.slices', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SLICEMETRICS_SLICE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=299,
)

_SLICEMETRICS_SLICE.containing_type = _SLICEMETRICS
_SLICEMETRICS.fields_by_name['slices'].message_type = _SLICEMETRICS_SLICE
DESCRIPTOR.message_types_by_name['SliceMetrics'] = _SLICEMETRICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SliceMetrics = _reflection.GeneratedProtocolMessageType('SliceMetrics', (_message.Message,), {

  'Slice' : _reflection.GeneratedProtocolMessageType('Slice', (_message.Message,), {
    'DESCRIPTOR' : _SLICEMETRICS_SLICE,
    '__module__' : 'slice_metrics_pb2'
    # @@protoc_insertion_point(class_scope:SliceMetrics.Slice)
    })
  ,
  'DESCRIPTOR' : _SLICEMETRICS,
  '__module__' : 'slice_metrics_pb2'
  # @@protoc_insertion_point(class_scope:SliceMetrics)
  })
_sym_db.RegisterMessage(SliceMetrics)
_sym_db.RegisterMessage(SliceMetrics.Slice)


# @@protoc_insertion_point(module_scope)
