// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slice_metrics.proto

#include "slice_metrics.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_slice_5fmetrics_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SliceMetrics_Slice_slice_5fmetrics_2eproto;
class SliceMetrics_SliceDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SliceMetrics_Slice> _instance;
} _SliceMetrics_Slice_default_instance_;
class SliceMetricsDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SliceMetrics> _instance;
} _SliceMetrics_default_instance_;
static void InitDefaultsscc_info_SliceMetrics_slice_5fmetrics_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_SliceMetrics_default_instance_;
    new (ptr) ::SliceMetrics();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::SliceMetrics::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_SliceMetrics_slice_5fmetrics_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_SliceMetrics_slice_5fmetrics_2eproto}, {
      &scc_info_SliceMetrics_Slice_slice_5fmetrics_2eproto.base,}};

static void InitDefaultsscc_info_SliceMetrics_Slice_slice_5fmetrics_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_SliceMetrics_Slice_default_instance_;
    new (ptr) ::SliceMetrics_Slice();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::SliceMetrics_Slice::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SliceMetrics_Slice_slice_5fmetrics_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_SliceMetrics_Slice_slice_5fmetrics_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_slice_5fmetrics_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_slice_5fmetrics_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_slice_5fmetrics_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_slice_5fmetrics_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::SliceMetrics_Slice, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::SliceMetrics_Slice, slice_id_),
  PROTOBUF_FIELD_OFFSET(::SliceMetrics_Slice, cfg_min_prb_),
  PROTOBUF_FIELD_OFFSET(::SliceMetrics_Slice, cfg_max_prb_),
  PROTOBUF_FIELD_OFFSET(::SliceMetrics_Slice, cfg_priority_),
  PROTOBUF_FIELD_OFFSET(::SliceMetrics_Slice, dl_rbs_used_),
  PROTOBUF_FIELD_OFFSET(::SliceMetrics_Slice, ul_rbs_used_),
  PROTOBUF_FIELD_OFFSET(::SliceMetrics_Slice, avg_dl_rbs_per_slot_),
  PROTOBUF_FIELD_OFFSET(::SliceMetrics_Slice, avg_ul_rbs_per_slot_),
  PROTOBUF_FIELD_OFFSET(::SliceMetrics_Slice, hol_slots_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::SliceMetrics, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::SliceMetrics, tti_),
  PROTOBUF_FIELD_OFFSET(::SliceMetrics, slices_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::SliceMetrics_Slice)},
  { 14, -1, sizeof(::SliceMetrics)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_SliceMetrics_Slice_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_SliceMetrics_default_instance_),
};

const char descriptor_table_protodef_slice_5fmetrics_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023slice_metrics.proto\"\223\002\n\014SliceMetrics\022\013"
  "\n\003tti\030\001 \001(\r\022#\n\006slices\030\002 \003(\0132\023.SliceMetri"
  "cs.Slice\032\320\001\n\005Slice\022\020\n\010slice_id\030\001 \001(\r\022\023\n\013"
  "cfg_min_prb\030\002 \001(\r\022\023\n\013cfg_max_prb\030\003 \001(\r\022\024"
  "\n\014cfg_priority\030\004 \001(\r\022\023\n\013dl_rbs_used\030\005 \001("
  "\r\022\023\n\013ul_rbs_used\030\006 \001(\r\022\033\n\023avg_dl_rbs_per"
  "_slot\030\007 \001(\002\022\033\n\023avg_ul_rbs_per_slot\030\010 \001(\002"
  "\022\021\n\thol_slots\030\t \001(\rb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_slice_5fmetrics_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_slice_5fmetrics_2eproto_sccs[2] = {
  &scc_info_SliceMetrics_slice_5fmetrics_2eproto.base,
  &scc_info_SliceMetrics_Slice_slice_5fmetrics_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_slice_5fmetrics_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_slice_5fmetrics_2eproto = {
  false, false, descriptor_table_protodef_slice_5fmetrics_2eproto, "slice_metrics.proto", 307,
  &descriptor_table_slice_5fmetrics_2eproto_once, descriptor_table_slice_5fmetrics_2eproto_sccs, descriptor_table_slice_5fmetrics_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_slice_5fmetrics_2eproto::offsets,
  file_level_metadata_slice_5fmetrics_2eproto, 2, file_level_enum_descriptors_slice_5fmetrics_2eproto, file_level_service_descriptors_slice_5fmetrics_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_slice_5fmetrics_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_slice_5fmetrics_2eproto)), true);

// ===================================================================

void SliceMetrics_Slice::InitAsDefaultInstance() {
}
class SliceMetrics_Slice::_Internal {
 public:
};

SliceMetrics_Slice::SliceMetrics_Slice(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:SliceMetrics.Slice)
}
SliceMetrics_Slice::SliceMetrics_Slice(const SliceMetrics_Slice& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&slice_id_, &from.slice_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&hol_slots_) -
    reinterpret_cast<char*>(&slice_id_)) + sizeof(hol_slots_));
  // @@protoc_insertion_point(copy_constructor:SliceMetrics.Slice)
}

void SliceMetrics_Slice::SharedCtor() {
  ::memset(&slice_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&hol_slots_) -
      reinterpret_cast<char*>(&slice_id_)) + sizeof(hol_slots_));
}

SliceMetrics_Slice::~SliceMetrics_Slice() {
  // @@protoc_insertion_point(destructor:SliceMetrics.Slice)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SliceMetrics_Slice::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void SliceMetrics_Slice::ArenaDtor(void* object) {
  SliceMetrics_Slice* _this = reinterpret_cast< SliceMetrics_Slice* >(object);
  (void)_this;
}
void SliceMetrics_Slice::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SliceMetrics_Slice::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SliceMetrics_Slice& SliceMetrics_Slice::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SliceMetrics_Slice_slice_5fmetrics_2eproto.base);
  return *internal_default_instance();
}


void SliceMetrics_Slice::Clear() {
// @@protoc_insertion_point(message_clear_start:SliceMetrics.Slice)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&slice_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&hol_slots_) -
      reinterpret_cast<char*>(&slice_id_)) + sizeof(hol_slots_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SliceMetrics_Slice::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 slice_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          slice_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 cfg_min_prb = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          cfg_min_prb_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 cfg_max_prb = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          cfg_max_prb_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 cfg_priority = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          cfg_priority_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 dl_rbs_used = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          dl_rbs_used_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 ul_rbs_used = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          ul_rbs_used_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // float avg_dl_rbs_per_slot = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 61)) {
          avg_dl_rbs_per_slot_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float avg_ul_rbs_per_slot = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 69)) {
          avg_ul_rbs_per_slot_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // uint32 hol_slots = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 72)) {
          hol_slots_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SliceMetrics_Slice::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SliceMetrics.Slice)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 slice_id = 1;
  if (this->slice_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_slice_id(), target);
  }

  // uint32 cfg_min_prb = 2;
  if (this->cfg_min_prb() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_cfg_min_prb(), target);
  }

  // uint32 cfg_max_prb = 3;
  if (this->cfg_max_prb() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_cfg_max_prb(), target);
  }

  // uint32 cfg_priority = 4;
  if (this->cfg_priority() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(4, this->_internal_cfg_priority(), target);
  }

  // uint32 dl_rbs_used = 5;
  if (this->dl_rbs_used() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(5, this->_internal_dl_rbs_used(), target);
  }

  // uint32 ul_rbs_used = 6;
  if (this->ul_rbs_used() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(6, this->_internal_ul_rbs_used(), target);
  }

  // float avg_dl_rbs_per_slot = 7;
  if (!(this->avg_dl_rbs_per_slot() <= 0 && this->avg_dl_rbs_per_slot() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(7, this->_internal_avg_dl_rbs_per_slot(), target);
  }

  // float avg_ul_rbs_per_slot = 8;
  if (!(this->avg_ul_rbs_per_slot() <= 0 && this->avg_ul_rbs_per_slot() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(8, this->_internal_avg_ul_rbs_per_slot(), target);
  }

  // uint32 hol_slots = 9;
  if (this->hol_slots() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(9, this->_internal_hol_slots(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SliceMetrics.Slice)
  return target;
}

size_t SliceMetrics_Slice::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SliceMetrics.Slice)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 slice_id = 1;
  if (this->slice_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_slice_id());
  }

  // uint32 cfg_min_prb = 2;
  if (this->cfg_min_prb() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_cfg_min_prb());
  }

  // uint32 cfg_max_prb = 3;
  if (this->cfg_max_prb() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_cfg_max_prb());
  }

  // uint32 cfg_priority = 4;
  if (this->cfg_priority() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_cfg_priority());
  }

  // uint32 dl_rbs_used = 5;
  if (this->dl_rbs_used() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_dl_rbs_used());
  }

  // uint32 ul_rbs_used = 6;
  if (this->ul_rbs_used() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_ul_rbs_used());
  }

  // float avg_dl_rbs_per_slot = 7;
  if (!(this->avg_dl_rbs_per_slot() <= 0 && this->avg_dl_rbs_per_slot() >= 0)) {
    total_size += 1 + 4;
  }

  // float avg_ul_rbs_per_slot = 8;
  if (!(this->avg_ul_rbs_per_slot() <= 0 && this->avg_ul_rbs_per_slot() >= 0)) {
    total_size += 1 + 4;
  }

  // uint32 hol_slots = 9;
  if (this->hol_slots() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_hol_slots());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SliceMetrics_Slice::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:SliceMetrics.Slice)
  GOOGLE_DCHECK_NE(&from, this);
  const SliceMetrics_Slice* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SliceMetrics_Slice>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:SliceMetrics.Slice)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:SliceMetrics.Slice)
    MergeFrom(*source);
  }
}

void SliceMetrics_Slice::MergeFrom(const SliceMetrics_Slice& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:SliceMetrics.Slice)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.slice_id() != 0) {
    _internal_set_slice_id(from._internal_slice_id());
  }
  if (from.cfg_min_prb() != 0) {
    _internal_set_cfg_min_prb(from._internal_cfg_min_prb());
  }
  if (from.cfg_max_prb() != 0) {
    _internal_set_cfg_max_prb(from._internal_cfg_max_prb());
  }
  if (from.cfg_priority() != 0) {
    _internal_set_cfg_priority(from._internal_cfg_priority());
  }
  if (from.dl_rbs_used() != 0) {
    _internal_set_dl_rbs_used(from._internal_dl_rbs_used());
  }
  if (from.ul_rbs_used() != 0) {
    _internal_set_ul_rbs_used(from._internal_ul_rbs_used());
  }
  if (!(from.avg_dl_rbs_per_slot() <= 0 && from.avg_dl_rbs_per_slot() >= 0)) {
    _internal_set_avg_dl_rbs_per_slot(from._internal_avg_dl_rbs_per_slot());
  }
  if (!(from.avg_ul_rbs_per_slot() <= 0 && from.avg_ul_rbs_per_slot() >= 0)) {
    _internal_set_avg_ul_rbs_per_slot(from._internal_avg_ul_rbs_per_slot());
  }
  if (from.hol_slots() != 0) {
    _internal_set_hol_slots(from._internal_hol_slots());
  }
}

void SliceMetrics_Slice::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:SliceMetrics.Slice)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SliceMetrics_Slice::CopyFrom(const SliceMetrics_Slice& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SliceMetrics.Slice)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SliceMetrics_Slice::IsInitialized() const {
  return true;
}

void SliceMetrics_Slice::InternalSwap(SliceMetrics_Slice* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SliceMetrics_Slice, hol_slots_)
      + sizeof(SliceMetrics_Slice::hol_slots_)
      - PROTOBUF_FIELD_OFFSET(SliceMetrics_Slice, slice_id_)>(
          reinterpret_cast<char*>(&slice_id_),
          reinterpret_cast<char*>(&other->slice_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SliceMetrics_Slice::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void SliceMetrics::InitAsDefaultInstance() {
}
class SliceMetrics::_Internal {
 public:
};

SliceMetrics::SliceMetrics(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  slices_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:SliceMetrics)
}
SliceMetrics::SliceMetrics(const SliceMetrics& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      slices_(from.slices_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  tti_ = from.tti_;
  // @@protoc_insertion_point(copy_constructor:SliceMetrics)
}

void SliceMetrics::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_SliceMetrics_slice_5fmetrics_2eproto.base);
  tti_ = 0u;
}

SliceMetrics::~SliceMetrics() {
  // @@protoc_insertion_point(destructor:SliceMetrics)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SliceMetrics::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void SliceMetrics::ArenaDtor(void* object) {
  SliceMetrics* _this = reinterpret_cast< SliceMetrics* >(object);
  (void)_this;
}
void SliceMetrics::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SliceMetrics::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SliceMetrics& SliceMetrics::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SliceMetrics_slice_5fmetrics_2eproto.base);
  return *internal_default_instance();
}


void SliceMetrics::Clear() {
// @@protoc_insertion_point(message_clear_start:SliceMetrics)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  slices_.Clear();
  tti_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SliceMetrics::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 tti = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          tti_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .SliceMetrics.Slice slices = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_slices(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SliceMetrics::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SliceMetrics)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 tti = 1;
  if (this->tti() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_tti(), target);
  }

  // repeated .SliceMetrics.Slice slices = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_slices_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_slices(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SliceMetrics)
  return target;
}

size_t SliceMetrics::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SliceMetrics)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .SliceMetrics.Slice slices = 2;
  total_size += 1UL * this->_internal_slices_size();
  for (const auto& msg : this->slices_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint32 tti = 1;
  if (this->tti() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_tti());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SliceMetrics::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:SliceMetrics)
  GOOGLE_DCHECK_NE(&from, this);
  const SliceMetrics* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SliceMetrics>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:SliceMetrics)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:SliceMetrics)
    MergeFrom(*source);
  }
}

void SliceMetrics::MergeFrom(const SliceMetrics& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:SliceMetrics)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  slices_.MergeFrom(from.slices_);
  if (from.tti() != 0) {
    _internal_set_tti(from._internal_tti());
  }
}

void SliceMetrics::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:SliceMetrics)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SliceMetrics::CopyFrom(const SliceMetrics& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SliceMetrics)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SliceMetrics::IsInitialized() const {
  return true;
}

void SliceMetrics::InternalSwap(SliceMetrics* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  slices_.InternalSwap(&other->slices_);
  swap(tti_, other->tti_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SliceMetrics::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::SliceMetrics_Slice* Arena::CreateMaybeMessage< ::SliceMetrics_Slice >(Arena* arena) {
  return Arena::CreateMessageInternal< ::SliceMetrics_Slice >(arena);
}
template<> PROTOBUF_NOINLINE ::SliceMetrics* Arena::CreateMaybeMessage< ::SliceMetrics >(Arena* arena) {
  return Arena::CreateMessageInternal< ::SliceMetrics >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
