// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slice_budgets.proto

#include "slice_budgets.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_slice_5fbudgets_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SliceBudgets_Budget_slice_5fbudgets_2eproto;
class SliceBudgets_BudgetDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SliceBudgets_Budget> _instance;
} _SliceBudgets_Budget_default_instance_;
class SliceBudgetsDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SliceBudgets> _instance;
} _SliceBudgets_default_instance_;
static void InitDefaultsscc_info_SliceBudgets_slice_5fbudgets_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_SliceBudgets_default_instance_;
    new (ptr) ::SliceBudgets();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::SliceBudgets::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_SliceBudgets_slice_5fbudgets_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_SliceBudgets_slice_5fbudgets_2eproto}, {
      &scc_info_SliceBudgets_Budget_slice_5fbudgets_2eproto.base,}};

static void InitDefaultsscc_info_SliceBudgets_Budget_slice_5fbudgets_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_SliceBudgets_Budget_default_instance_;
    new (ptr) ::SliceBudgets_Budget();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::SliceBudgets_Budget::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SliceBudgets_Budget_slice_5fbudgets_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_SliceBudgets_Budget_slice_5fbudgets_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_slice_5fbudgets_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_slice_5fbudgets_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_slice_5fbudgets_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_slice_5fbudgets_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::SliceBudgets_Budget, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::SliceBudgets_Budget, slice_id_),
  PROTOBUF_FIELD_OFFSET(::SliceBudgets_Budget, min_prb_),
  PROTOBUF_FIELD_OFFSET(::SliceBudgets_Budget, max_prb_),
  PROTOBUF_FIELD_OFFSET(::SliceBudgets_Budget, priority_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::SliceBudgets, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::SliceBudgets, tti_),
  PROTOBUF_FIELD_OFFSET(::SliceBudgets, budgets_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::SliceBudgets_Budget)},
  { 9, -1, sizeof(::SliceBudgets)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_SliceBudgets_Budget_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_SliceBudgets_default_instance_),
};

const char descriptor_table_protodef_slice_5fbudgets_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023slice_budgets.proto\"\222\001\n\014SliceBudgets\022\013"
  "\n\003tti\030\001 \001(\r\022%\n\007budgets\030\002 \003(\0132\024.SliceBudg"
  "ets.Budget\032N\n\006Budget\022\020\n\010slice_id\030\001 \001(\r\022\017"
  "\n\007min_prb\030\002 \001(\r\022\017\n\007max_prb\030\003 \001(\r\022\020\n\010prio"
  "rity\030\004 \001(\rb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_slice_5fbudgets_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_slice_5fbudgets_2eproto_sccs[2] = {
  &scc_info_SliceBudgets_slice_5fbudgets_2eproto.base,
  &scc_info_SliceBudgets_Budget_slice_5fbudgets_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_slice_5fbudgets_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_slice_5fbudgets_2eproto = {
  false, false, descriptor_table_protodef_slice_5fbudgets_2eproto, "slice_budgets.proto", 178,
  &descriptor_table_slice_5fbudgets_2eproto_once, descriptor_table_slice_5fbudgets_2eproto_sccs, descriptor_table_slice_5fbudgets_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_slice_5fbudgets_2eproto::offsets,
  file_level_metadata_slice_5fbudgets_2eproto, 2, file_level_enum_descriptors_slice_5fbudgets_2eproto, file_level_service_descriptors_slice_5fbudgets_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_slice_5fbudgets_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_slice_5fbudgets_2eproto)), true);

// ===================================================================

void SliceBudgets_Budget::InitAsDefaultInstance() {
}
class SliceBudgets_Budget::_Internal {
 public:
};

SliceBudgets_Budget::SliceBudgets_Budget(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:SliceBudgets.Budget)
}
SliceBudgets_Budget::SliceBudgets_Budget(const SliceBudgets_Budget& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&slice_id_, &from.slice_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&priority_) -
    reinterpret_cast<char*>(&slice_id_)) + sizeof(priority_));
  // @@protoc_insertion_point(copy_constructor:SliceBudgets.Budget)
}

void SliceBudgets_Budget::SharedCtor() {
  ::memset(&slice_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&priority_) -
      reinterpret_cast<char*>(&slice_id_)) + sizeof(priority_));
}

SliceBudgets_Budget::~SliceBudgets_Budget() {
  // @@protoc_insertion_point(destructor:SliceBudgets.Budget)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SliceBudgets_Budget::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void SliceBudgets_Budget::ArenaDtor(void* object) {
  SliceBudgets_Budget* _this = reinterpret_cast< SliceBudgets_Budget* >(object);
  (void)_this;
}
void SliceBudgets_Budget::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SliceBudgets_Budget::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SliceBudgets_Budget& SliceBudgets_Budget::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SliceBudgets_Budget_slice_5fbudgets_2eproto.base);
  return *internal_default_instance();
}


void SliceBudgets_Budget::Clear() {
// @@protoc_insertion_point(message_clear_start:SliceBudgets.Budget)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&slice_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&priority_) -
      reinterpret_cast<char*>(&slice_id_)) + sizeof(priority_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SliceBudgets_Budget::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 slice_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          slice_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 min_prb = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          min_prb_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 max_prb = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          max_prb_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 priority = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          priority_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SliceBudgets_Budget::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SliceBudgets.Budget)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 slice_id = 1;
  if (this->slice_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_slice_id(), target);
  }

  // uint32 min_prb = 2;
  if (this->min_prb() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_min_prb(), target);
  }

  // uint32 max_prb = 3;
  if (this->max_prb() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_max_prb(), target);
  }

  // uint32 priority = 4;
  if (this->priority() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(4, this->_internal_priority(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SliceBudgets.Budget)
  return target;
}

size_t SliceBudgets_Budget::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SliceBudgets.Budget)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 slice_id = 1;
  if (this->slice_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_slice_id());
  }

  // uint32 min_prb = 2;
  if (this->min_prb() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_min_prb());
  }

  // uint32 max_prb = 3;
  if (this->max_prb() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_max_prb());
  }

  // uint32 priority = 4;
  if (this->priority() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_priority());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SliceBudgets_Budget::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:SliceBudgets.Budget)
  GOOGLE_DCHECK_NE(&from, this);
  const SliceBudgets_Budget* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SliceBudgets_Budget>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:SliceBudgets.Budget)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:SliceBudgets.Budget)
    MergeFrom(*source);
  }
}

void SliceBudgets_Budget::MergeFrom(const SliceBudgets_Budget& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:SliceBudgets.Budget)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.slice_id() != 0) {
    _internal_set_slice_id(from._internal_slice_id());
  }
  if (from.min_prb() != 0) {
    _internal_set_min_prb(from._internal_min_prb());
  }
  if (from.max_prb() != 0) {
    _internal_set_max_prb(from._internal_max_prb());
  }
  if (from.priority() != 0) {
    _internal_set_priority(from._internal_priority());
  }
}

void SliceBudgets_Budget::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:SliceBudgets.Budget)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SliceBudgets_Budget::CopyFrom(const SliceBudgets_Budget& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SliceBudgets.Budget)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SliceBudgets_Budget::IsInitialized() const {
  return true;
}

void SliceBudgets_Budget::InternalSwap(SliceBudgets_Budget* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SliceBudgets_Budget, priority_)
      + sizeof(SliceBudgets_Budget::priority_)
      - PROTOBUF_FIELD_OFFSET(SliceBudgets_Budget, slice_id_)>(
          reinterpret_cast<char*>(&slice_id_),
          reinterpret_cast<char*>(&other->slice_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SliceBudgets_Budget::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void SliceBudgets::InitAsDefaultInstance() {
}
class SliceBudgets::_Internal {
 public:
};

SliceBudgets::SliceBudgets(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  budgets_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:SliceBudgets)
}
SliceBudgets::SliceBudgets(const SliceBudgets& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      budgets_(from.budgets_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  tti_ = from.tti_;
  // @@protoc_insertion_point(copy_constructor:SliceBudgets)
}

void SliceBudgets::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_SliceBudgets_slice_5fbudgets_2eproto.base);
  tti_ = 0u;
}

SliceBudgets::~SliceBudgets() {
  // @@protoc_insertion_point(destructor:SliceBudgets)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SliceBudgets::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void SliceBudgets::ArenaDtor(void* object) {
  SliceBudgets* _this = reinterpret_cast< SliceBudgets* >(object);
  (void)_this;
}
void SliceBudgets::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SliceBudgets::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SliceBudgets& SliceBudgets::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SliceBudgets_slice_5fbudgets_2eproto.base);
  return *internal_default_instance();
}


void SliceBudgets::Clear() {
// @@protoc_insertion_point(message_clear_start:SliceBudgets)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  budgets_.Clear();
  tti_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SliceBudgets::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 tti = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          tti_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .SliceBudgets.Budget budgets = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_budgets(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SliceBudgets::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SliceBudgets)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 tti = 1;
  if (this->tti() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_tti(), target);
  }

  // repeated .SliceBudgets.Budget budgets = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_budgets_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_budgets(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SliceBudgets)
  return target;
}

size_t SliceBudgets::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SliceBudgets)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .SliceBudgets.Budget budgets = 2;
  total_size += 1UL * this->_internal_budgets_size();
  for (const auto& msg : this->budgets_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint32 tti = 1;
  if (this->tti() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_tti());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SliceBudgets::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:SliceBudgets)
  GOOGLE_DCHECK_NE(&from, this);
  const SliceBudgets* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SliceBudgets>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:SliceBudgets)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:SliceBudgets)
    MergeFrom(*source);
  }
}

void SliceBudgets::MergeFrom(const SliceBudgets& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:SliceBudgets)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  budgets_.MergeFrom(from.budgets_);
  if (from.tti() != 0) {
    _internal_set_tti(from._internal_tti());
  }
}

void SliceBudgets::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:SliceBudgets)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SliceBudgets::CopyFrom(const SliceBudgets& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SliceBudgets)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SliceBudgets::IsInitialized() const {
  return true;
}

void SliceBudgets::InternalSwap(SliceBudgets* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  budgets_.InternalSwap(&other->budgets_);
  swap(tti_, other->tti_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SliceBudgets::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::SliceBudgets_Budget* Arena::CreateMaybeMessage< ::SliceBudgets_Budget >(Arena* arena) {
  return Arena::CreateMessageInternal< ::SliceBudgets_Budget >(arena);
}
template<> PROTOBUF_NOINLINE ::SliceBudgets* Arena::CreateMaybeMessage< ::SliceBudgets >(Arena* arena) {
  return Arena::CreateMessageInternal< ::SliceBudgets >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
