// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slice_metrics.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_slice_5fmetrics_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_slice_5fmetrics_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#if defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wextra-semi"
#endif
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_slice_5fmetrics_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_slice_5fmetrics_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_slice_5fmetrics_2eproto;
class SliceMetrics;
class SliceMetricsDefaultTypeInternal;
extern SliceMetricsDefaultTypeInternal _SliceMetrics_default_instance_;
class SliceMetrics_Slice;
class SliceMetrics_SliceDefaultTypeInternal;
extern SliceMetrics_SliceDefaultTypeInternal _SliceMetrics_Slice_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::SliceMetrics* Arena::CreateMaybeMessage<::SliceMetrics>(Arena*);
template<> ::SliceMetrics_Slice* Arena::CreateMaybeMessage<::SliceMetrics_Slice>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class SliceMetrics_Slice PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SliceMetrics.Slice) */ {
 public:
  inline SliceMetrics_Slice() : SliceMetrics_Slice(nullptr) {};
  virtual ~SliceMetrics_Slice();

  SliceMetrics_Slice(const SliceMetrics_Slice& from);
  SliceMetrics_Slice(SliceMetrics_Slice&& from) noexcept
    : SliceMetrics_Slice() {
    *this = ::std::move(from);
  }

  inline SliceMetrics_Slice& operator=(const SliceMetrics_Slice& from) {
    CopyFrom(from);
    return *this;
  }
  inline SliceMetrics_Slice& operator=(SliceMetrics_Slice&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SliceMetrics_Slice& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SliceMetrics_Slice* internal_default_instance() {
    return reinterpret_cast<const SliceMetrics_Slice*>(
               &_SliceMetrics_Slice_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SliceMetrics_Slice& a, SliceMetrics_Slice& b) {
    a.Swap(&b);
  }
  inline void Swap(SliceMetrics_Slice* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SliceMetrics_Slice* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SliceMetrics_Slice* New() const final {
    return CreateMaybeMessage<SliceMetrics_Slice>(nullptr);
  }

  SliceMetrics_Slice* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SliceMetrics_Slice>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SliceMetrics_Slice& from);
  void MergeFrom(const SliceMetrics_Slice& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SliceMetrics_Slice* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SliceMetrics.Slice";
  }
  protected:
  explicit SliceMetrics_Slice(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_slice_5fmetrics_2eproto);
    return ::descriptor_table_slice_5fmetrics_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSliceIdFieldNumber = 1,
    kCfgMinPrbFieldNumber = 2,
    kCfgMaxPrbFieldNumber = 3,
    kCfgPriorityFieldNumber = 4,
    kDlRbsUsedFieldNumber = 5,
    kUlRbsUsedFieldNumber = 6,
    kAvgDlRbsPerSlotFieldNumber = 7,
    kAvgUlRbsPerSlotFieldNumber = 8,
    kHolSlotsFieldNumber = 9,
  };
  // uint32 slice_id = 1;
  void clear_slice_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 slice_id() const;
  void set_slice_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_slice_id() const;
  void _internal_set_slice_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 cfg_min_prb = 2;
  void clear_cfg_min_prb();
  ::PROTOBUF_NAMESPACE_ID::uint32 cfg_min_prb() const;
  void set_cfg_min_prb(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_cfg_min_prb() const;
  void _internal_set_cfg_min_prb(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 cfg_max_prb = 3;
  void clear_cfg_max_prb();
  ::PROTOBUF_NAMESPACE_ID::uint32 cfg_max_prb() const;
  void set_cfg_max_prb(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_cfg_max_prb() const;
  void _internal_set_cfg_max_prb(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 cfg_priority = 4;
  void clear_cfg_priority();
  ::PROTOBUF_NAMESPACE_ID::uint32 cfg_priority() const;
  void set_cfg_priority(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_cfg_priority() const;
  void _internal_set_cfg_priority(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 dl_rbs_used = 5;
  void clear_dl_rbs_used();
  ::PROTOBUF_NAMESPACE_ID::uint32 dl_rbs_used() const;
  void set_dl_rbs_used(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_dl_rbs_used() const;
  void _internal_set_dl_rbs_used(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 ul_rbs_used = 6;
  void clear_ul_rbs_used();
  ::PROTOBUF_NAMESPACE_ID::uint32 ul_rbs_used() const;
  void set_ul_rbs_used(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_ul_rbs_used() const;
  void _internal_set_ul_rbs_used(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // float avg_dl_rbs_per_slot = 7;
  void clear_avg_dl_rbs_per_slot();
  float avg_dl_rbs_per_slot() const;
  void set_avg_dl_rbs_per_slot(float value);
  private:
  float _internal_avg_dl_rbs_per_slot() const;
  void _internal_set_avg_dl_rbs_per_slot(float value);
  public:

  // float avg_ul_rbs_per_slot = 8;
  void clear_avg_ul_rbs_per_slot();
  float avg_ul_rbs_per_slot() const;
  void set_avg_ul_rbs_per_slot(float value);
  private:
  float _internal_avg_ul_rbs_per_slot() const;
  void _internal_set_avg_ul_rbs_per_slot(float value);
  public:

  // uint32 hol_slots = 9;
  void clear_hol_slots();
  ::PROTOBUF_NAMESPACE_ID::uint32 hol_slots() const;
  void set_hol_slots(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_hol_slots() const;
  void _internal_set_hol_slots(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:SliceMetrics.Slice)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 slice_id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 cfg_min_prb_;
  ::PROTOBUF_NAMESPACE_ID::uint32 cfg_max_prb_;
  ::PROTOBUF_NAMESPACE_ID::uint32 cfg_priority_;
  ::PROTOBUF_NAMESPACE_ID::uint32 dl_rbs_used_;
  ::PROTOBUF_NAMESPACE_ID::uint32 ul_rbs_used_;
  float avg_dl_rbs_per_slot_;
  float avg_ul_rbs_per_slot_;
  ::PROTOBUF_NAMESPACE_ID::uint32 hol_slots_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_slice_5fmetrics_2eproto;
};
// -------------------------------------------------------------------

class SliceMetrics PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SliceMetrics) */ {
 public:
  inline SliceMetrics() : SliceMetrics(nullptr) {};
  virtual ~SliceMetrics();

  SliceMetrics(const SliceMetrics& from);
  SliceMetrics(SliceMetrics&& from) noexcept
    : SliceMetrics() {
    *this = ::std::move(from);
  }

  inline SliceMetrics& operator=(const SliceMetrics& from) {
    CopyFrom(from);
    return *this;
  }
  inline SliceMetrics& operator=(SliceMetrics&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SliceMetrics& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SliceMetrics* internal_default_instance() {
    return reinterpret_cast<const SliceMetrics*>(
               &_SliceMetrics_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SliceMetrics& a, SliceMetrics& b) {
    a.Swap(&b);
  }
  inline void Swap(SliceMetrics* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SliceMetrics* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SliceMetrics* New() const final {
    return CreateMaybeMessage<SliceMetrics>(nullptr);
  }

  SliceMetrics* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SliceMetrics>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SliceMetrics& from);
  void MergeFrom(const SliceMetrics& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SliceMetrics* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SliceMetrics";
  }
  protected:
  explicit SliceMetrics(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_slice_5fmetrics_2eproto);
    return ::descriptor_table_slice_5fmetrics_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef SliceMetrics_Slice Slice;

  // accessors -------------------------------------------------------

  enum : int {
    kSlicesFieldNumber = 2,
    kTtiFieldNumber = 1,
  };
  // repeated .SliceMetrics.Slice slices = 2;
  int slices_size() const;
  private:
  int _internal_slices_size() const;
  public:
  void clear_slices();
  ::SliceMetrics_Slice* mutable_slices(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SliceMetrics_Slice >*
      mutable_slices();
  private:
  const ::SliceMetrics_Slice& _internal_slices(int index) const;
  ::SliceMetrics_Slice* _internal_add_slices();
  public:
  const ::SliceMetrics_Slice& slices(int index) const;
  ::SliceMetrics_Slice* add_slices();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SliceMetrics_Slice >&
      slices() const;

  // uint32 tti = 1;
  void clear_tti();
  ::PROTOBUF_NAMESPACE_ID::uint32 tti() const;
  void set_tti(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_tti() const;
  void _internal_set_tti(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:SliceMetrics)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SliceMetrics_Slice > slices_;
  ::PROTOBUF_NAMESPACE_ID::uint32 tti_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_slice_5fmetrics_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SliceMetrics_Slice

// uint32 slice_id = 1;
inline void SliceMetrics_Slice::clear_slice_id() {
  slice_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SliceMetrics_Slice::_internal_slice_id() const {
  return slice_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SliceMetrics_Slice::slice_id() const {
  // @@protoc_insertion_point(field_get:SliceMetrics.Slice.slice_id)
  return _internal_slice_id();
}
inline void SliceMetrics_Slice::_internal_set_slice_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  slice_id_ = value;
}
inline void SliceMetrics_Slice::set_slice_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_slice_id(value);
  // @@protoc_insertion_point(field_set:SliceMetrics.Slice.slice_id)
}

// uint32 cfg_min_prb = 2;
inline void SliceMetrics_Slice::clear_cfg_min_prb() {
  cfg_min_prb_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SliceMetrics_Slice::_internal_cfg_min_prb() const {
  return cfg_min_prb_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SliceMetrics_Slice::cfg_min_prb() const {
  // @@protoc_insertion_point(field_get:SliceMetrics.Slice.cfg_min_prb)
  return _internal_cfg_min_prb();
}
inline void SliceMetrics_Slice::_internal_set_cfg_min_prb(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  cfg_min_prb_ = value;
}
inline void SliceMetrics_Slice::set_cfg_min_prb(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_cfg_min_prb(value);
  // @@protoc_insertion_point(field_set:SliceMetrics.Slice.cfg_min_prb)
}

// uint32 cfg_max_prb = 3;
inline void SliceMetrics_Slice::clear_cfg_max_prb() {
  cfg_max_prb_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SliceMetrics_Slice::_internal_cfg_max_prb() const {
  return cfg_max_prb_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SliceMetrics_Slice::cfg_max_prb() const {
  // @@protoc_insertion_point(field_get:SliceMetrics.Slice.cfg_max_prb)
  return _internal_cfg_max_prb();
}
inline void SliceMetrics_Slice::_internal_set_cfg_max_prb(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  cfg_max_prb_ = value;
}
inline void SliceMetrics_Slice::set_cfg_max_prb(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_cfg_max_prb(value);
  // @@protoc_insertion_point(field_set:SliceMetrics.Slice.cfg_max_prb)
}

// uint32 cfg_priority = 4;
inline void SliceMetrics_Slice::clear_cfg_priority() {
  cfg_priority_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SliceMetrics_Slice::_internal_cfg_priority() const {
  return cfg_priority_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SliceMetrics_Slice::cfg_priority() const {
  // @@protoc_insertion_point(field_get:SliceMetrics.Slice.cfg_priority)
  return _internal_cfg_priority();
}
inline void SliceMetrics_Slice::_internal_set_cfg_priority(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  cfg_priority_ = value;
}
inline void SliceMetrics_Slice::set_cfg_priority(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_cfg_priority(value);
  // @@protoc_insertion_point(field_set:SliceMetrics.Slice.cfg_priority)
}

// uint32 dl_rbs_used = 5;
inline void SliceMetrics_Slice::clear_dl_rbs_used() {
  dl_rbs_used_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SliceMetrics_Slice::_internal_dl_rbs_used() const {
  return dl_rbs_used_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SliceMetrics_Slice::dl_rbs_used() const {
  // @@protoc_insertion_point(field_get:SliceMetrics.Slice.dl_rbs_used)
  return _internal_dl_rbs_used();
}
inline void SliceMetrics_Slice::_internal_set_dl_rbs_used(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  dl_rbs_used_ = value;
}
inline void SliceMetrics_Slice::set_dl_rbs_used(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_dl_rbs_used(value);
  // @@protoc_insertion_point(field_set:SliceMetrics.Slice.dl_rbs_used)
}

// uint32 ul_rbs_used = 6;
inline void SliceMetrics_Slice::clear_ul_rbs_used() {
  ul_rbs_used_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SliceMetrics_Slice::_internal_ul_rbs_used() const {
  return ul_rbs_used_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SliceMetrics_Slice::ul_rbs_used() const {
  // @@protoc_insertion_point(field_get:SliceMetrics.Slice.ul_rbs_used)
  return _internal_ul_rbs_used();
}
inline void SliceMetrics_Slice::_internal_set_ul_rbs_used(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  ul_rbs_used_ = value;
}
inline void SliceMetrics_Slice::set_ul_rbs_used(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_ul_rbs_used(value);
  // @@protoc_insertion_point(field_set:SliceMetrics.Slice.ul_rbs_used)
}

// float avg_dl_rbs_per_slot = 7;
inline void SliceMetrics_Slice::clear_avg_dl_rbs_per_slot() {
  avg_dl_rbs_per_slot_ = 0;
}
inline float SliceMetrics_Slice::_internal_avg_dl_rbs_per_slot() const {
  return avg_dl_rbs_per_slot_;
}
inline float SliceMetrics_Slice::avg_dl_rbs_per_slot() const {
  // @@protoc_insertion_point(field_get:SliceMetrics.Slice.avg_dl_rbs_per_slot)
  return _internal_avg_dl_rbs_per_slot();
}
inline void SliceMetrics_Slice::_internal_set_avg_dl_rbs_per_slot(float value) {
  
  avg_dl_rbs_per_slot_ = value;
}
inline void SliceMetrics_Slice::set_avg_dl_rbs_per_slot(float value) {
  _internal_set_avg_dl_rbs_per_slot(value);
  // @@protoc_insertion_point(field_set:SliceMetrics.Slice.avg_dl_rbs_per_slot)
}

// float avg_ul_rbs_per_slot = 8;
inline void SliceMetrics_Slice::clear_avg_ul_rbs_per_slot() {
  avg_ul_rbs_per_slot_ = 0;
}
inline float SliceMetrics_Slice::_internal_avg_ul_rbs_per_slot() const {
  return avg_ul_rbs_per_slot_;
}
inline float SliceMetrics_Slice::avg_ul_rbs_per_slot() const {
  // @@protoc_insertion_point(field_get:SliceMetrics.Slice.avg_ul_rbs_per_slot)
  return _internal_avg_ul_rbs_per_slot();
}
inline void SliceMetrics_Slice::_internal_set_avg_ul_rbs_per_slot(float value) {
  
  avg_ul_rbs_per_slot_ = value;
}
inline void SliceMetrics_Slice::set_avg_ul_rbs_per_slot(float value) {
  _internal_set_avg_ul_rbs_per_slot(value);
  // @@protoc_insertion_point(field_set:SliceMetrics.Slice.avg_ul_rbs_per_slot)
}

// uint32 hol_slots = 9;
inline void SliceMetrics_Slice::clear_hol_slots() {
  hol_slots_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SliceMetrics_Slice::_internal_hol_slots() const {
  return hol_slots_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SliceMetrics_Slice::hol_slots() const {
  // @@protoc_insertion_point(field_get:SliceMetrics.Slice.hol_slots)
  return _internal_hol_slots();
}
inline void SliceMetrics_Slice::_internal_set_hol_slots(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  hol_slots_ = value;
}
inline void SliceMetrics_Slice::set_hol_slots(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_hol_slots(value);
  // @@protoc_insertion_point(field_set:SliceMetrics.Slice.hol_slots)
}

// -------------------------------------------------------------------

// SliceMetrics

// uint32 tti = 1;
inline void SliceMetrics::clear_tti() {
  tti_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SliceMetrics::_internal_tti() const {
  return tti_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SliceMetrics::tti() const {
  // @@protoc_insertion_point(field_get:SliceMetrics.tti)
  return _internal_tti();
}
inline void SliceMetrics::_internal_set_tti(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  tti_ = value;
}
inline void SliceMetrics::set_tti(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_tti(value);
  // @@protoc_insertion_point(field_set:SliceMetrics.tti)
}

// repeated .SliceMetrics.Slice slices = 2;
inline int SliceMetrics::_internal_slices_size() const {
  return slices_.size();
}
inline int SliceMetrics::slices_size() const {
  return _internal_slices_size();
}
inline void SliceMetrics::clear_slices() {
  slices_.Clear();
}
inline ::SliceMetrics_Slice* SliceMetrics::mutable_slices(int index) {
  // @@protoc_insertion_point(field_mutable:SliceMetrics.slices)
  return slices_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SliceMetrics_Slice >*
SliceMetrics::mutable_slices() {
  // @@protoc_insertion_point(field_mutable_list:SliceMetrics.slices)
  return &slices_;
}
inline const ::SliceMetrics_Slice& SliceMetrics::_internal_slices(int index) const {
  return slices_.Get(index);
}
inline const ::SliceMetrics_Slice& SliceMetrics::slices(int index) const {
  // @@protoc_insertion_point(field_get:SliceMetrics.slices)
  return _internal_slices(index);
}
inline ::SliceMetrics_Slice* SliceMetrics::_internal_add_slices() {
  return slices_.Add();
}
inline ::SliceMetrics_Slice* SliceMetrics::add_slices() {
  // @@protoc_insertion_point(field_add:SliceMetrics.slices)
  return _internal_add_slices();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SliceMetrics_Slice >&
SliceMetrics::slices() const {
  // @@protoc_insertion_point(field_list:SliceMetrics.slices)
  return slices_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#if defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_slice_5fmetrics_2eproto
