# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: slice_budgets.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='slice_budgets.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13slice_budgets.proto\"\x92\x01\n\x0cSliceBudgets\x12\x0b\n\x03tti\x18\x01 \x01(\r\x12%\n\x07\x62udgets\x18\x02 \x03(\x0b\x32\x14.SliceBudgets.Budget\x1aN\n\x06\x42udget\x12\x10\n\x08slice_id\x18\x01 \x01(\r\x12\x0f\n\x07min_prb\x18\x02 \x01(\r\x12\x0f\n\x07max_prb\x18\x03 \x01(\r\x12\x10\n\x08priority\x18\x04 \x01(\rb\x06proto3'
)




_SLICEBUDGETS_BUDGET = _descriptor.Descriptor(
  name='Budget',
  full_name='SliceBudgets.Budget',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='slice_id', full_name='SliceBudgets.Budget.slice_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_prb', full_name='SliceBudgets.Budget.min_prb', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_prb', full_name='SliceBudgets.Budget.max_prb', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='priority', full_name='SliceBudgets.Budget.priority', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=170,
)

_SLICEBUDGETS = _descriptor.Descriptor(
  name='SliceBudgets',
  full_name='SliceBudgets',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tti', full_name='SliceBudgets.tti', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='budgets', full_name='SliceBudgets.budgets', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SLICEBUDGETS_BUDGET, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=170,
)

_SLICEBUDGETS_BUDGET.containing_type = _SLICEBUDGETS
_SLICEBUDGETS.fields_by_name['budgets'].message_type = _SLICEBUDGETS_BUDGET
DESCRIPTOR.message_types_by_name['SliceBudgets'] = _SLICEBUDGETS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SliceBudgets = _reflection.GeneratedProtocolMessageType('SliceBudgets', (_message.Message,), {

  'Budget' : _reflection.GeneratedProtocolMessageType('Budget', (_message.Message,), {
    'DESCRIPTOR' : _SLICEBUDGETS_BUDGET,
    '__module__' : 'slice_budgets_pb2'
    # @@protoc_insertion_point(class_scope:SliceBudgets.Budget)
    })
  ,
  'DESCRIPTOR' : _SLICEBUDGETS,
  '__module__' : 'slice_budgets_pb2'
  # @@protoc_insertion_point(class_scope:SliceBudgets)
  })
_sym_db.RegisterMessage(SliceBudgets)
_sym_db.RegisterMessage(SliceBudgets.Budget)


# @@protoc_insertion_point(module_scope)
